[package]
name = "fido-key-wrap"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[features]
testing = []

[dependencies]
aes-gcm.workspace = true
# enable aes round-key cleanup and ghash construction-temporary cleanup.
aes.workspace = true
ghash.workspace = true
argon2.workspace = true
fido-key-wrap-libfido2 = { path = "../fido-key-wrap-libfido2" }
getrandom.workspace = true
hkdf.workspace = true
hmac.workspace = true
minicbor.workspace = true
p256.workspace = true
sha2.workspace = true
subtle.workspace = true
thiserror.workspace = true
zeroize.workspace = true

[lints]
workspace = true
