[package]
name = "fkw-demo"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[[bin]]
name = "fkw"
path = "src/main.rs"

[dependencies]
aes-gcm.workspace = true
anyhow.workspace = true
clap.workspace = true
fido-key-wrap = { path = "../fido-key-wrap" }
fs2.workspace = true
getrandom.workspace = true
hkdf.workspace = true
libc.workspace = true
rpassword.workspace = true
sha2.workspace = true
zeroize.workspace = true

[lints]
workspace = true
