[package]
name = "fkw-demo"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[features]
default = ["fido"]
fido = ["fido-key-wrap/fido"]

[dependencies]
anyhow.workspace = true
clap.workspace = true
fido-key-wrap = { path = "../fido-key-wrap", default-features = false }
rpassword.workspace = true
subtle.workspace = true

[lints]
workspace = true
