[package]
name = "fkw-demo"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
clap.workspace = true
fido-key-wrap = { path = "../fido-key-wrap" }
rpassword.workspace = true
subtle.workspace = true

[lints]
workspace = true
