[package]
name = "fido-key-wrap-python"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[lib]
name = "_native"
crate-type = ["cdylib", "rlib"]

[dependencies]
fido-key-wrap = { path = "../fido-key-wrap" }
pyo3.workspace = true
zeroize.workspace = true

[lints]
workspace = true
